/* eslint-disable @next/next/no-img-element */
import type { Metadata } from "next";
import { ArrowLeft, ArrowRight, ArrowUpRight, Asterisk, Check, Play } from "lucide-react";

import { createPageMetadata } from "@/lib/metadata";
import { withBasePath } from "@/lib/site-data";

export const metadata: Metadata = createPageMetadata({ title: "Spartan AI", description: "Scale your ideas. Build with AI.", path: "/" });

const a = (name: string) => withBasePath(`/spartan-reference/${name}`);
const projects = [
  ["cigna-smart-health-systems", "HEALTHCARE AI", "Cigna Smart Health Systems", "sZxYLpvH56E3RznKPcnAPYlPvo.jpg", "$45M+", "700%", "41x", "84"],
  ["aetna-health-data-ecosystem", "HEALTHCARE", "Aetna Health Data Ecosystem", "4GMiBYbu9SI4dXo9ENcqlNA.jpg", "$62M+", "450%", "32x", "91"],
  ["anthem-neural-care-network", "HEALTHCARE", "Anthem Neural Care Network", "ZK0k9kMGgE21P7r3puSMYZ8548.jpg", "$82M+", "340%", "19x", "56"],
  ["cvs-smart-supply-chain-hub", "RETAIL & LOGISTICS", "CVS Smart Supply Chain Hub", "0g3E5eja3ueYAXkITtsy9quyYo.jpg", "$59M+", "215%", "73x", "28"],
  ["united-ai-security-protocol", "CYBERSECURITY", "United AI Security Protocol", "LYQLqywSoqlHG7KLRJM70MIk.png", "$94M+", "120%", "66x", "12"],
] as const;
const experiences = [
  ["MARCUS CHENG", "Head of AI, Aetna", "The custom agentic workflows they built reduced our manual data entry by 90%, saving us hundreds of hours weekly.", "9AvPLCB2PkQCEoFgNdwvDaIaGGI.jpg"],
  ["DAVID ROSSI", "Lead Dev, Cigna", "Their team didn't just provide tools; they provided a roadmap for AI integration that actually makes sense for ROI.", "rLkyXpp1TSaADDj0EYjy9c8uw.jpg"],
  ["SARAH JENKINS", "CTO, Anthem Group", "A game-changer for our R&D. The neural infrastructure is robust, secure, and perfectly tailored to our niche stack.", "IIK9uqdpvVqpPgAHuhf8s9r4Ee4.jpg"],
  ["ELENA VANCE", "VP Eng, UnitedHealth", "Incredible technical depth. They handled our complex RAG implementation with ease and delivered ahead of schedule.", "QHChEEbpWFuUCrhS6zqN5BK4Rr0.jpg"],
] as const;
const team = [
  ["SARAH JENKINS", "Head of Machine Learning", "Our focus remains on the ethical deployment of large-scale models. We don't just optimize for performance; we ensure every neural architecture we build is interpretable, secure, and ready for enterprise-grade scrutiny.", "D3gag0wTRQzvb6CCfJkTShmXTPI.jpg"],
  ["MARCUS CHENG", "Principal Design Director", "AI shouldn't feel like a black box. My goal is to design intuitive interfaces that make complex data actionable, ensuring that the human-machine collaboration is seamless, visually stunning, and highly efficient for users.", "9AvPLCB2PkQCEoFgNdwvDaIaGGI.jpg"],
  ["ELENA VANCE", "Lead Cognitive Scientist", "We study the cognitive friction between AI output and human decision-making. By applying behavioral science to our agentic workflows, we create tools that naturally align with how your best employees actually think and work.", "pktP7O1JHzk75RWizEsb0jRSjk.jpg"],
  ["DAVID ROSSI", "Infrastructure Architect", "Latency is the enemy of adoption. I architect the backbone of our solutions to ensure that even the most complex RAG systems deliver sub-second responses, maintaining 99.9% uptime across distributed global compute clusters.", "2418vQBGZ7CPVHaaIlQ5wuUyr4.jpg"],
] as const;
const plans = [
  ["Core", "495", "618", "Automate your repetitive tasks.", "3 Automation Flows", "Standard RAG Support", "1 Admin Seat", "Discord Support"],
  ["Growth", "1,250", "1,570", "Advanced agentic workflows.", "10 Automation Flows", "Vector DB Hosting", "5 Admin Seats", "Priority Email"],
  ["Pro", "2,900", "3,650", "Custom neural architecture.", "Unlimited Flows", "Custom Fine-Tuning", "15 Admin Seats", "24/7 Slack Connect"],
  ["Scale", "7,500", "9,380", "Enterprise infrastructure.", "Full Neural Stack", "On-Premise LLMs", "Unlimited Seats", "Dedicated Engineer"],
] as const;
const faqs = [
  ["How do you ensure our data remains secure?", "We utilize SOC2-compliant local vector databases and on-premise LLM hosting to ensure your proprietary data never leaves your infrastructure."],
  ["What is the typical deployment timeline?", "Most custom deployments move from strategic audit to production-ready infrastructure in a focused, iterative delivery cycle."],
  ["Can we integrate with our existing CRM?", "Yes. We design integrations around your current stack, data permissions, and operational workflows."],
  ["Do you provide model fine-tuning?", "Yes. Fine-tuning, retrieval systems, evaluation, and model routing are available where the use case requires them."],
  ["How do you calculate ROI for automation?", "We baseline time, cost, quality, and throughput before deployment, then measure the same signals after launch."],
  ["Do we own the custom code you build?", "Yes. Custom architecture and implementation are transferred according to the terms of your engagement."],
  ["What models do you specialize in?", "We work across leading open and proprietary models, choosing the stack that best fits your security, latency, and quality requirements."],
] as const;
const articles = [
  ["the-sovereign-cloud-why-on-premise-ai-is-the-future-of-data-privacy", "TRANSFORMATION", "The Sovereign Cloud: Why On-Premise AI is the Future of Data Privacy", "Explore how federated learning and private hosting are allowing firms to innovate without risking security.", "Frank Joel", "YKAEpvQFebP2OETEJDVNip8UTg.jpeg"],
  ["the-architecture-of-autonomy-scaling-ai-within-legacy-frameworks", "ARCHITECTURE", "The Architecture of Autonomy: Scaling AI Within Legacy Frameworks", "A comprehensive guide on integrating custom machine learning models into complex enterprise environments.", "Damilola Manuel", "862JbA3xEJjbdSDVyKEwOZ0f2g.jpeg"],
  ["human-centric-automation-designing-ai-that-empowers-your-workforce", "PRIVACY", "Human-Centric Automation: Designing AI That Empowers Your Workforce", "Why the most successful AI implementations focus on augmenting human talent rather than simply replacing it.", "Deborah Reachie", "egDVD5dc2AvUIZKG0seuGXtH0.jpeg"],
] as const;

function Ticker() { return <div className="replica-ticker"><b><i />{"//SPARTAN"}</b><p>We are officially expanding our neural compute clusters to three new global regions, providing sub-50ms inference speeds for our enterprise partners across EMEA, APAC, and North America.</p></div>; }

export default function HomePage() {
  return <main id="main-content" className="replica-home">
    <section className="replica-hero" data-motion-section>
      <img className="hero-landscape" src={a("PXNhr4LbXoJRWLAHfzNTYjvdR5Y.png")} alt="" />
      <div className="hero-copy"><h1><span>Scale your ideas.</span> Build with AI.</h1><p>Deploy custom neural agents, LLMs, and automation in one seamless flow.</p><a className="round-cta" href={withBasePath("/contact/")}><span>⌁</span> Start Build</a></div>
      <a className="brain-card" href={withBasePath("/digital-brain/")}><video src={a("2WO0ZC7yTbYNkxdTbPKkcOs30s.mp4")} autoPlay muted loop playsInline /><div><span><b>Digital Brain</b><small>{"// Model v4.0.2"}</small></span><ArrowRight /></div></a>
      <p className="deploy-copy">+2,400 active deployments and 8,200 brands trust our high-performance architecture.</p>
      <div className="client-logos">{["FIkeNB0CMpKHgxqL0a3aPHKlAyQ.png","nJbNnh8E8FlHfzjwzNY6HTfjGnE.png","C7otSLQhZagCjkAC4M6MX1Ns.png","3EwtMm1CTn3V13Xu2ufZVUnW4.png","PNxA5d1umCQiNSezotkgCnArwqU.png"].map((logo)=><img key={logo} src={a(logo)} alt="" />)}</div>
    </section>

    <section className="replica-impact" data-motion-section><div className="impact-copy"><h2>Automate the manual, accelerate the future. Our custom AI solutions deliver measurable growth and operational excellence.</h2><p>Empowering teams with intelligent tools that turn complex data into actionable business outcomes daily.</p></div><div className="metric-grid"><article className="metric-revenue"><strong>$45M</strong><p>Revenue generated for our clients through AI-led optimizations.</p></article><article className="metric-agents"><div>{["D3gag0wTRQzvb6CCfJkTShmXTPI.jpg","9AvPLCB2PkQCEoFgNdwvDaIaGGI.jpg","pktP7O1JHzk75RWizEsb0jRSjk.jpg","2418vQBGZ7CPVHaaIlQ5wuUyr4.jpg"].map(x=><img key={x} src={a(x)} alt="" />)}</div><strong>15,400 <small>active agents</small></strong></article><article className="metric-speed"><strong>5x</strong><p>Faster speed to market.</p></article><article className="metric-inference"><strong>90%</strong><h3>Inference speed</h3><p>Real-time processing for enterprise-grade deployments.</p></article><blockquote>The custom LLM they built for us reduced our support tickets by 80% while increasing user satisfaction.<cite>• CTO, Cigna</cite></blockquote></div><Ticker /></section>

    <section className="replica-works" data-motion-section><div className="mega-title"><h2>Our Works</h2><Asterisk /></div><div className="works-grid">{projects.map((p,i)=><a href={withBasePath(`/project/${p[0]}/`)} className={`work-card work-${i+1}`} key={p[0]}><div className="work-image"><img src={a(p[3])} alt="" /><span>{p[1]}</span></div><h3>{p[2]}</h3><div className="work-stats"><span><b>{p[4]}</b>Funds raised</span><span><b>{p[5]}</b>Social growth</span><span><b>{p[6]}</b>ATH ROI</span><span><b>{p[7]}</b>Partnerships</span></div></a>)}</div></section>

    <section className="replica-capabilities" id="capabilities" data-motion-section><div className="cap-head"><div><b>CAPABILITIES</b><p>We bridge the gap between abstract machine learning and practical business utility through bespoke engineering.</p></div><h2>Tailored Intelligence for Modern Enterprises.</h2><a className="light-cta" href={withBasePath("/contact/")}>Start Build <ArrowUpRight /></a></div><div className="cap-panels"><article className="is-active"><button data-capability="0"><span>001</span>AUTONOMOUS AGENT ARCHITECTURE LABS</button><div><h3>Autonomous Agent Architecture Labs</h3><p>Architecting robust server environments and local LLM integrations to ensure data remains secure and local.</p></div></article><article><button data-capability="1"><span>002</span>AUTONOMOUS AGENTIC WORKFLOWS</button><div><h3>Autonomous Agentic Workflows</h3><p>Designing intelligent workflows that reason, coordinate tools, and complete multi-step work at enterprise scale.</p></div></article><article><button data-capability="2"><span>003</span>DATA PIPELINES &amp; RAG SYSTEMS</button><div><h3>Data Pipelines &amp; RAG Systems</h3><p>Connecting trusted enterprise context to accurate retrieval and production-ready neural systems.</p></div></article></div><div className="vision-grid"><article><div className="founder"><span>ALEXANDER VACCA</span><small>Founder &amp; Lead Engineer</small></div><b>OUR VISION</b><h3>We believe that AI should not just automate tasks, but amplify the creative and strategic potential of every human.</h3><p>By merging technical rigor with intuitive design, we build systems that don&apos;t just solve problems—they create entirely new opportunities for growth.</p></article><a className="brain-feature" href={withBasePath("/digital-brain/")}><p>ENGINEERING SYSTEMS THAT SCALE WITH YOUR AMBITION. WE LEVERAGE INDUSTRY-LEADING MODELS TO DEPLOY CUSTOM NEURAL SOLUTIONS TAILORED TO YOUR STACK.</p><video src={a("2WO0ZC7yTbYNkxdTbPKkcOs30s.mp4")} autoPlay muted loop playsInline /><b>Digital Brain <small>v4.0.2</small></b></a><article className="language-card"><p>Semantic vector search for hyper-accurate retrieval</p><p>Unified data lakes for expansive model context.</p><p>Token-optimized flows for high speed processing</p><div>ZH HI ES FR AR BN PT RU EN DE</div><small>Global LLM deployment. Support for 95+ languages.</small></article></div></section>

    <section className="replica-experiences" data-motion-section><div className="mega-title"><h2>Experiences</h2><Asterisk /></div><div className="experience-top"><p>Empowering global enterprises through bespoke neural architectures and autonomous agentic workflows.</p><div><button data-carousel-prev aria-label="Previous"><ArrowLeft /></button><button data-carousel-next aria-label="Next"><ArrowRight /></button></div></div><div className="experience-rail" data-carousel role="region" aria-label="Client experiences" tabIndex={0}>{experiences.map((x)=><article key={x[0]}><img src={a(x[3])} alt="" /><p>{x[2]}</p><footer><b>{x[0]}</b><span>{x[1]}</span></footer></article>)}</div><Ticker /></section>

    <section className="replica-film" style={{backgroundImage:`url(${a("v2cZIMtgjEII7EpDnUDGGgCyuiQ.png")})`}} data-motion-section><div><p>Exploring the intersection of human creativity and machine logic to redefine what&apos;s possible in the digital age.</p><span>2mins watch</span></div><h2>Intelligence by Design.</h2><button aria-label="Play film"><Play /></button></section>

    <section className="replica-process" data-motion-section><b>OUR PROCESS</b><h2>From raw data to refined intelligence. Our iterative deployment cycle.</h2><div className="process-panels">{[["01","Comprehensive Strategic Audit","AUDIT","We perform a deep-layer analysis of your current technical stack and fragmented data silos to identify high-impact AI opportunities that align with your core business objectives and ROI targets."],["02","Custom Architecture Design","DESIGN","We map the model, data, interface, and infrastructure required for your custom neural system."],["03","Rapid Prototype Development","DEVELOP","We build and test the highest-value workflows in focused production sprints."],["04","Enterprise Scale Deployment","DEPLOY","We harden, monitor, and scale your system across the environments where it creates value."]].map((x,i)=><article className={i===0?"is-active":""} key={x[0]}><button data-process={i}><span>{`// ${x[0]}`}</span>{x[1]}</button><div><b>{x[2]}</b><p>{x[3]}</p></div></article>)}</div><aside><p>WE DON&apos;T JUST SHIP CODE; WE SHIP COMPETITIVE ADVANTAGES. EVERY STEP IS DESIGNED TO ENSURE YOUR AI INFRASTRUCTURE IS FUTURE-PROOF AND SCALABLE.</p><a href={withBasePath("/contact/")}>Build Now <ArrowUpRight /></a></aside></section>

    <section className="replica-team" data-motion-section><div className="team-intro"><h2>We are a collective of engineers, designers, and researchers dedicated to the frontier of AI.</h2><div><p>Bridging the gap between academic research and commercial deployment with precision engineering.</p><a href={withBasePath("/about/")}>Our Story <ArrowRight /></a></div></div><div className="team-grid">{team.map((x)=><article key={x[0]}><header><h3>{x[0]}</h3><span>{x[1]}</span></header><p>{x[2]}</p><img src={a(x[3])} alt="" /><footer><b>{x[0]}</b><span>{x[1]}</span></footer></article>)}</div></section>

    <section className="replica-pricing" id="pricing" data-motion-section><div className="mega-title dark"><h2>Pricing</h2><Asterisk /></div><div className="pricing-top"><p>Flexible intelligence tiers designed to scale alongside your business. No hidden costs, just high-performance results.</p><div className="billing-toggle" role="group" aria-label="Billing period"><button data-billing="monthly" aria-pressed="false">Monthly</button><button className="is-active" data-billing="annual" aria-pressed="true">Annually <small>(Save 20%)</small></button></div></div><div className="pricing-grid">{plans.map((x)=><article key={x[0]}><h3>{x[0]}</h3><div className="price"><span>$</span><strong data-price data-annual={x[1]} data-monthly={x[2]}>{x[1]}</strong><small>/mo</small></div><em>USD Billed <span data-billing-label>Annually</span></em><p>{x[3]}</p><a href="https://contra.com/sirdelani/work?r=sirdelani">Get started <ArrowUpRight /></a><ul>{x.slice(4).map(f=><li key={f}><Check />{f}</li>)}</ul></article>)}</div><Ticker /></section>

    <section className="replica-faq" data-motion-section><div className="faq-intro"><div><b>COMMON QUERIES</b><p>Find answers to technical specifications, deployment timelines, and our data security protocols.</p></div><div><h2>Everything you need to know about our AI.</h2><a href={withBasePath("/contact/")}>Contact Support <ArrowRight /></a></div></div><div className="faq-list">{faqs.map((x,i)=><details open={i===0} key={x[0]}><summary><h3>{x[0]}</h3><span>+</span></summary><p>{x[1]}</p></details>)}</div></section>

    <section className="replica-insights" data-motion-section><div className="mega-title"><h2>Insights</h2><Asterisk /></div><div className="insights-top"><p>A curated repository of technical frameworks, model benchmarks, and strategic guides for leaders navigating the integration of custom neural architectures.</p><a href={withBasePath("/articles/")}>All articles <ArrowRight /></a></div><div className="article-grid">{articles.map(x=><a href={withBasePath(`/articles/${x[0]}/`)} key={x[0]}><img src={a(x[5])} alt="" /><span>{x[1]}</span><h3>{x[2]}</h3><p>{x[3]}</p><small>Written by {x[4]}</small></a>)}</div><a className="template-banner" href="https://www.framer.com/marketplace/templates/spartans/"><span>Buy Spartan AI Template</span><b>from <strong>$129</strong></b></a></section>
  </main>;
}
