/* eslint-disable @next/next/no-img-element */
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { getArticleBySlug,spartanSiteContent as content } from "@/content/spartan-site-content";
import { createPageMetadata } from "@/lib/metadata";
import { withBasePath } from "@/lib/site-data";

export function generateStaticParams(){return content.articles.map(({slug})=>({slug}))}
export async function generateMetadata({params}:PageProps<"/articles/[slug]">):Promise<Metadata>{const item=getArticleBySlug((await params).slug);return item?createPageMetadata({title:item.title,description:item.description,path:`/articles/${item.slug}/`,type:"article"}):{}}
const data={"the-sovereign-cloud-why-on-premise-ai-is-the-future-of-data-privacy":{image:"862JbA3xEJjbdSDVyKEwOZ0f2g.jpeg",author:"Frank Joel",date:"Mar 4, 2026",quote:"In the digital age, data sovereignty is not just a legal requirement—it is a strategic fortress.",heads:["Shift Toward Private Intelligence","Pillars of Secure AI","Understanding Federated Learning","Compliance as a Competitive Edge","Cost of Insecurity","Conclusion: Future-Proofing the Enterprise"]},"the-architecture-of-autonomy-scaling-ai-within-legacy-frameworks":{image:"YKAEpvQFebP2OETEJDVNip8UTg.jpeg",author:"Damilola Manuel",date:"Feb 12, 2026",quote:"Legacy systems are not an anchor; they are a goldmine of institutional knowledge waiting for an intelligent interface.",heads:["Foundation of Enterprise Intelligence","1. Data Harmonization","Specialized vs. General Models","Implementation Challenges and Solutions","Human-in-the-Loop","Predictive Enterprise"]},"human-centric-automation-designing-ai-that-empowers-your-workforce":{image:"egDVD5dc2AvUIZKG0seuGXtH0.jpeg",author:"Deborah Reachie",date:"Mar 15, 2026",quote:"Technology reaches its zenith not when it acts independently, but when it expands the capability of every person using it.",heads:["Augmentation Era","Three Levels of Augmentation","Intuition and Trust","ROI of Employee Satisfaction","Empowered Agent","Future Built Together"]}} as const;
export default async function ArticleDetailPage({params}:PageProps<"/articles/[slug]">){const article=getArticleBySlug((await params).slug);if(!article)notFound();const info=data[article.slug as keyof typeof data];return <main id="main-content" className="reference-inner article-detail-replica"><img className="article-detail-hero" src={withBasePath(`/spartan-reference/${info.image}`)} alt=""/><header><span>{article.category}</span><h1>{article.title}</h1><p>{article.description}</p><div><b>AUTHOR<small>{info.author}</small></b><b>PUBLISHED<small>{info.date}</small></b></div></header><article className="editorial-body"><h2>{info.quote}</h2>{info.heads.map((heading,index)=><section key={heading}><h3>{heading}</h3><p>{article.sections[index%article.sections.length].body}</p></section>)}</article><section className="more-insights"><h2>More Insights</h2><div>{content.articles.filter(x=>x.slug!==article.slug).map(x=><a href={withBasePath(`/articles/${x.slug}/`)} key={x.slug}><span>{x.category}</span><h3>{x.title}</h3></a>)}</div></section></main>}
