/* eslint-disable @next/next/no-img-element */
import type { Metadata } from "next";
import { ArrowUpRight } from "lucide-react";
import { ReferenceFaq } from "@/components/reference-faq";
import { createPageMetadata } from "@/lib/metadata";
import { withBasePath } from "@/lib/site-data";

export const metadata:Metadata=createPageMetadata({title:"Digital Brain",description:"Own Your Private Neural Engine",path:"/digital-brain/"});
const a=(name:string)=>withBasePath(`/spartan-reference/${name}`);
export default function DigitalBrainPage(){return <main id="main-content" className="reference-inner brain-replica"><section className="brain-hero"><div className="brain-proof"><div>{["D3gag0wTRQzvb6CCfJkTShmXTPI.jpg","9AvPLCB2PkQCEoFgNdwvDaIaGGI.jpg","pktP7O1JHzk75RWizEsb0jRSjk.jpg","2418vQBGZ7CPVHaaIlQ5wuUyr4.jpg"].map(x=><img src={a(x)} key={x} alt=""/>)}</div><span>OVER 3000 HAPPY FOUNDERS<br/>AROUND THE WORLD</span></div><h1>Own Your Private Neural Engine</h1><p>Deploy a secure, pre-trained AI brain that masters your enterprise data in milliseconds.</p><a href="https://contra.com/sirdelani/work?r=sirdelani">Buy This Engine <ArrowUpRight/></a><img className="brain-hero-image" src={a("w75Htm3EMyaVPyezz0MRi3jeE3U.jpeg")} alt=""/></section><section className="brain-metrics">{[["$M","Cloud-cost reduction"],["99%","Triage accuracy"],["10x","Processing speed"],["25ms","Local edge latency"]].map(x=><article key={x[1]}><strong>{x[0]}</strong><span>{x[1]}</span></article>)}</section><section className="brain-command"><h2>Neural Operations Command</h2><p>Monitor, train, and deploy your private intelligence from one secure operating layer.</p><img src={a("EN5qmomOAWObQ8Fy9alqxLF90.png")} alt="Neural operations command dashboard"/><div className="brain-stories"><article><img src={a("2jfGwg9j23wnTy8hryN5C9OGR84.jpg")} alt=""/><h3>Instant Strategic Scoping</h3><p>Turn complex enterprise context into clear priorities, decisions, and next actions.</p></article><article><img src={a("ohsFgOykFQhHVTtmKUZxlqXbOGs.jpg")} alt=""/><h3>Autonomous Growth Engine</h3><p>Coordinate intelligent systems that learn from approved data and execute at scale.</p></article></div></section><section className="brain-manifesto"><b>DIGITAL BRAIN v4.0.2</b><h2>A private neural layer engineered to understand your enterprise, reason across its systems, and act with speed.</h2><a href="https://contra.com/sirdelani/work?r=sirdelani">Buy This Engine <ArrowUpRight/></a><div className="brain-status"><span>SYSTEM STATUS: OPTIMIZED</span><p>One control plane for secure training, model orchestration, local deployment, and continuous evaluation.</p></div><div className="brain-benefits">{[["Private by design","Train on sensitive enterprise data without exposing it."],["Collaborative intelligence","Connect specialized Brain instances across teams."],["Edge deployment","Run low-latency intelligence where your operations happen."],["Native integrations","Connect SQL, ERP, CRM, and existing enterprise systems."]].map((x,i)=><article key={x[0]}><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></section><ReferenceFaq/></main>}
